export const careerRoles = [
  { name: "Engineers", week: "A week may move between calculations, design reviews and questions from a live site. The task is to turn requirements into details that can be built and maintained.", learning: "How design assumptions hold up against ground conditions, budgets and construction sequence.", alongside: "Other engineers, site teams and the people making decisions for the client." },
  { name: "Architects", week: "You may develop layouts, review drawings and work through the junctions between space, structure and services. A small change on paper can make a building easier to use.", learning: "How spatial choices affect construction, access and the building's daily operation.", alongside: "Engineers, project leads and the people responsible for turning drawings into work on site." },
  { name: "Site Engineers", week: "Site work may include reviewing drawings, observing progress and recording questions that need a decision. Clear notes help keep the design office and site working from the same information.", learning: "How sequencing, materials and small dimensional details affect the next stage of work.", alongside: "Supervisors, construction teams and the engineers responsible for the design." },
  { name: "Trainees", week: "Depending on the project, you may help organise technical records, review a drawing with a colleague or follow a calculation through its assumptions. The emphasis is on understanding why a decision was made.", learning: "Practical habits for checking work, recording evidence and asking a useful question.", alongside: "Experienced colleagues who can explain the task and review your contribution." },
  { name: "Interns", week: "An assignment might involve research, drawing checks or preparing information for a project discussion. Tasks depend on the work available and your current experience.", learning: "How a project moves between people, documents and decisions, and where your own interests fit.", alongside: "Project colleagues from engineering, design and delivery." },
  { name: "Data Analyst", week: "You may organise project or asset data, check its quality and explore patterns in reports and dashboards. The aim is to turn records into clear information that supports a decision.", learning: "How to test assumptions, explain findings and connect analysis to the questions a project needs to answer.", alongside: "Engineers, asset management colleagues and project teams who collect and use the information." },
  { name: "Information system specialist", week: "You may review how information moves between teams, support the systems they use and help organise reliable project records. Tasks could include documenting workflows, checking access or investigating an issue.", learning: "How systems, data quality and everyday working practices fit together across a project's life.", alongside: "Project teams, technical colleagues and the people responsible for managing information and digital tools." },
] as const;
